### PR TITLE
adds mobile game dev fridays group

### PR DESCRIPTION
**Pull request by JimLynchCodes**
👾

### CODE REVIEW

**Comment by mightyiam** [comment]
Thank you @JimLynchCodes for making the effort.

Here's an error. Ideally, it would be more useful.

https://github.com/mobusoperandi/website/actions/runs/10751871553/job/29819562238?pr=257#step:8:518

hrm... sorry, I don't get it. You have any thoughts perhaps?

**Comment by JimLynchCodes** [comment]
Thanks @mightyiam

I think I was using an invalid value for the "status"... or possible the colors. But I just changed both of those things, and it seems to build fine for me locally so I'm hoping that it will go fine on ci now. I don't see how I can get to the run for this commit though.

**Comment by mightyiam** [comment]
It's set up in a way that CI runs must be approved individually. Which I just did. So let's see.

**Comment by JimLynchCodes** [comment]
@mightyiam I think the build completely successfully right? 

Can you merge pls so I can start telling people about the meeting tomorrow :)

**Comment by mightyiam** [comment]
Sorry. Can't seem to do on the phone. Tomorrow then.

**Review by mightyiam — APPROVED** [review]
I'm not sure what's going on with the deployment not finding some secret. I'm sure I had this set up correctly at some point. Thinking it might be waiting for an approving review (long shot).

**Comment by JimLynchCodes** [comment]
Woo, I can see it now! I think I did the date math incorrectly though bc it's showing up at the wrong time of day... 😅

I'll fix it and open another PR

**Pull request merged**
