### PR TITLE
fixes game dev fridays time

### PR DESCRIPTION
**Pull request by JimLynchCodes**
Kind of embarrassing that I messed this up... 😅

This time should be correct now, 3pm eastern time 👍

### CODE REVIEW

**Comment by mightyiam** [comment]
Well, if it's eastern time then it should be eastern time instead of UTC. This matters because of DST.

**Comment by mightyiam** [comment]
Your call, of course.

**Comment by JimLynchCodes** [comment]
Ah, good call. Ok I think I have changed it use 3pm EST now 👍

**Comment by JimLynchCodes** [comment]
Hey @mightyiam, do you know why the website is still showing the wrong time? We merged it but seems like it didn’t redeploy…

**Pull request merged**
